### ISSUE TITLE
Softlock on Episode 4, Level 1

### ISSUE THREAD

**Issue by Techbane** [opentyrian/opentyrian#9] opened 2020-07-15 16:16 UTC
So far I've verified this happens on Linux Mint with the version downloaded through the Software Manager, and the Raspberry Pi build downloaded through RetroPie. Just go straight to the first level of Episode 4, whether in Full Game or Arcade mode, and the sub-boss maybe a minute into the level (a giant stone arch shooting electricity, flanked by a few pyramids) has a broken health bar. Beating it doesn't cause the level to start scrolling again, so you're locked in place.

**Comment by carlreinke** [comment] 2020-07-15 21:04
What difficulty level?

Can you try the latest master?  I wasn't able to reproduce the bug on normal difficulty.

**Comment by KScl** [comment] 2020-07-16 00:31
I'm relatively certain this is the same bug I experienced and fixed with 325bf4e.

**Comment by carlreinke** [comment] 2020-08-15 20:44
Feel free to reopen this issue if the issue is reproducible using a build from master.

**Closed by carlreinke** 2020-08-15 20:44 UTC
