### ISSUE TITLE
OpenTyrian only shows part of the screen on some Wayland compositors

### ISSUE THREAD

**Issue by vanfanel** [opentyrian/opentyrian#53] opened 2022-10-12 19:16 UTC
Hi there,

On Wayland compositors like all the ones based on WLRoots and others, only a part of the screen in OpenTyrian  is visible in fullscreen mode.

I thought it was an SDL2/Wayland problem, so I opened an issue on their repository:
https://github.com/libsdl-org/SDL/issues/6354

But in the end, SDL2 devs have concluded it's an OpenTyrian problem. From the SDL2 issue thread:

> 
> The main problem this game seems to have is that it doesn't seem to be processing messages or flipping the buffers when there's no animation occurring onscreen unless input events occur, so any window messages such as resizes or going in/out of fullscreen won't be processed until something occurs that causes the game to process it's message loop or flip the buffers and subsequently process the Wayland message loop.
> 
> Running it with Wayland debug output shows everything coming to a complete halt when the game logos or menu are static unless some input occurs. Everything just stops, which is why the game seems to fix itself when some animation occurs from the menus cross-fading since the message queue is processed.
> 
> Not really something that can be fixed on SDL's end. This game has to run it's message loop more often.

So, can it be fixed on OpenTyrian?

**Comment by carlreinke** [comment] 2022-10-13 04:23
From the SDL issue, it wasn't clear to me whether the problem is not flipping buffers or not consuming events (or both).

Could you provide some examples of when the problem occurs and when it goes away (if it does)?

**Comment by vanfanel** [comment] 2022-10-13 10:36
Yes: the problem is happening during the EPIC logo only.
Only a small square of the image is visible while the logo fades-in, and while the logo remains static.
Then, just when the EPIC logo starts to fade out, the whole image becomes visible and the problem doesn't appear again.

**Comment by carlreinke** [comment] 2022-10-15 18:28
Should be fixed as of 62468e341981a8461ec9c632cc4dd96badb7db59.

**Closed by carlreinke** 2022-10-15 18:28 UTC

**Comment by vanfanel** [comment] 2022-10-16 04:26
@carlreinke Yes, perfect now. thanks a lot for taking a look at this, really :)
