### ISSUE TITLE
End of level destruction glitch

### ISSUE THREAD

**Issue by JackNWhite** [opentyrian/opentyrian#55] opened 2022-11-30 23:19 UTC
I have glitched past the end of the first level of episode 2. My ship was destroyed right at the same time as the boss ship, and then my ship reappeared in the normal way, but there are no enemies, and the background has kept shifting until it's locked into a corner.

![Screenshot from 2022-12-01 00-11-01](https://user-images.githubusercontent.com/10062543/204927925-f8c14932-c2da-4f0d-b6f5-2931a8fe633a.png)

Probably, 20-something years later, nobody wants to fix it, but I just thought I'd throw it out there!

**Comment by carlreinke** [comment] 2022-12-01 01:20
Duplicate of #17.

**Closed by carlreinke** 2022-12-01 01:20 UTC
